// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: apps/user/pb/rpc.proto

package app01

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListUserReq) Reset() {
	*x = ListUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_app01_pb_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserReq) ProtoMessage() {}

func (x *ListUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_app01_pb_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserReq.ProtoReflect.Descriptor instead.
func (*ListUserReq) Descriptor() ([]byte, []int) {
	return file_apps_app01_pb_rpc_proto_rawDescGZIP(), []int{0}
}

var File_apps_app01_pb_rpc_proto protoreflect.FileDescriptor

var file_apps_app01_pb_rpc_proto_rawDesc = []byte{
	0x0a, 0x17, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x61, 0x70, 0x70, 0x30, 0x31, 0x2f, 0x70, 0x62, 0x2f,
	0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x69, 0x6e, 0x66, 0x72, 0x61,
	0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x61, 0x70, 0x70, 0x30, 0x31, 0x1a, 0x19,
	0x61, 0x70, 0x70, 0x73, 0x2f, 0x61, 0x70, 0x70, 0x30, 0x31, 0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0d, 0x0a, 0x0b, 0x4c, 0x69, 0x73,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x32, 0x9a, 0x01, 0x0a, 0x07, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x22,
	0x2e, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x61,
	0x70, 0x70, 0x30, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x1a, 0x19, 0x2e, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x2e, 0x61, 0x70, 0x70, 0x30, 0x31, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x12, 0x46, 0x0a,
	0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x20, 0x2e, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2e, 0x65, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x61, 0x70, 0x70, 0x30, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2e,
	0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x61, 0x70, 0x70, 0x30, 0x31, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x53, 0x65, 0x74, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x71, 0x69, 0x61, 0x6f, 0x67, 0x79, 0x39, 0x31, 0x2f, 0x69, 0x6f, 0x63,
	0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x61, 0x70,
	0x70, 0x30, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apps_app01_pb_rpc_proto_rawDescOnce sync.Once
	file_apps_app01_pb_rpc_proto_rawDescData = file_apps_app01_pb_rpc_proto_rawDesc
)

func file_apps_app01_pb_rpc_proto_rawDescGZIP() []byte {
	file_apps_app01_pb_rpc_proto_rawDescOnce.Do(func() {
		file_apps_app01_pb_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_apps_app01_pb_rpc_proto_rawDescData)
	})
	return file_apps_app01_pb_rpc_proto_rawDescData
}

var file_apps_app01_pb_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_apps_app01_pb_rpc_proto_goTypes = []any{
	(*ListUserReq)(nil),   // 0: infra.example.user.ListUserReq
	(*CreateUserReq)(nil), // 1: infra.example.user.CreateUserReq
	(*User)(nil),          // 2: infra.example.user.User
	(*UserSet)(nil),       // 3: infra.example.user.UserSet
}
var file_apps_app01_pb_rpc_proto_depIdxs = []int32{
	1, // 0: infra.example.user.Service.Create:input_type -> infra.example.user.CreateUserReq
	0, // 1: infra.example.user.Service.List:input_type -> infra.example.user.ListUserReq
	2, // 2: infra.example.user.Service.Create:output_type -> infra.example.user.User
	3, // 3: infra.example.user.Service.List:output_type -> infra.example.user.UserSet
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apps_app01_pb_rpc_proto_init() }
func file_apps_app01_pb_rpc_proto_init() {
	if File_apps_app01_pb_rpc_proto != nil {
		return
	}
	file_apps_app01_pb_model_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_apps_app01_pb_rpc_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ListUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apps_app01_pb_rpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_app01_pb_rpc_proto_goTypes,
		DependencyIndexes: file_apps_app01_pb_rpc_proto_depIdxs,
		MessageInfos:      file_apps_app01_pb_rpc_proto_msgTypes,
	}.Build()
	File_apps_app01_pb_rpc_proto = out.File
	file_apps_app01_pb_rpc_proto_rawDesc = nil
	file_apps_app01_pb_rpc_proto_goTypes = nil
	file_apps_app01_pb_rpc_proto_depIdxs = nil
}
